/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HALF_half */

#ifndef _Included_HALF_half
#define _Included_HALF_half
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HALF_half
 * Method:    DevN
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_HALF_half_DevN
  (JNIEnv *, jobject);

/*
 * Class:     HALF_half
 * Method:    DevD
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_HALF_half_DevD
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif